ASPP_adpative: true
image_D: multi_patch
content_D: DMPHN
G: BRR_DMPHN_1_2_4_8
Norm: leaky
Pixel_adaptive_conv: true
batch_size: 6
per_pix_kernel: 3
channel: 32
experiment_name: BRR_DMPHN_1_2_4_8_c32
gan_type: RaGAN
gpu: 0
image_size: 256
isGAN: false
isTrain: true
lambda_adv: 0
lambda_content: 0
lambda_pixel: 1
lambda_offset: 0
learning_rate: 0.0001  
start_train_epoch: 770
train_epoch: 3000
Recurrent_times: 3
alignment: FPN
           