ASPP_adpative: true
image_D: multi_patch
content_D: DMPHN
G: Patch_Motion_SFT_fusion
Norm: leaky
Pixel_adaptive_conv: true
batch_size: 3
channel: 32
experiment_name: Patch_Motion_SFT_fusion_c32
gan_type: RaGAN
gpu: 0
image_size: 256
isGAN: false
isTrain: true
lambda_adv: 0
lambda_content: 0
lambda_pixel: 1
lambda_offset: 0
learning_rate: 0.0001  
start_train_epoch: 0
train_epoch: 2400
Recurrent_times: 2
alignment: FPN
           