ASPP_adpative: true
D: Patch_Deblur_FPN
G: Patch_Deblur_FPN_VAE
Norm: None
Pixel_adaptive_conv: true
batch_size: 6
channel: 64
experiment_name: FPN_ECA_group_c64
gan_type: RaGAN
gpu: 0
image_size: 256
isGAN: false
isTrain: true
lambda_adv: 0
lambda_class: 0
lambda_content: 0
lambda_pixel: 1
learning_rate: 0.0001
start_train_epoch: 0
train_epoch: 500
